set(kconfig_env_dirs)
list(APPEND kconfig_env_dirs ZEPHYR_WEATHER_STATION_MODULE_DIR=/__w/weather-station/weather-station)
list(APPEND kconfig_env_dirs ZEPHYR_CMSIS_6_MODULE_DIR=/__w/weather-station/modules/hal/cmsis_6)
list(APPEND kconfig_env_dirs ZEPHYR_HAL_NORDIC_MODULE_DIR=/__w/weather-station/modules/hal/nordic)
list(APPEND kconfig_env_dirs ZEPHYR_HAL_NXP_MODULE_DIR=/__w/weather-station/modules/hal/nxp)
list(APPEND kconfig_env_dirs ZEPHYR_HAL_ST_MODULE_DIR=/__w/weather-station/modules/hal/st)
list(APPEND kconfig_env_dirs ZEPHYR_HAL_STM32_MODULE_DIR=/__w/weather-station/modules/hal/stm32)
list(APPEND kconfig_env_dirs ZEPHYR_LORAMAC_NODE_MODULE_DIR=/__w/weather-station/modules/lib/loramac-node)
list(APPEND kconfig_env_dirs ZEPHYR_LVGL_MODULE_DIR=/__w/weather-station/modules/lib/gui/lvgl)
list(APPEND kconfig_env_dirs ZEPHYR_MBEDTLS_MODULE_DIR=/__w/weather-station/modules/crypto/mbedtls)
list(APPEND kconfig_env_dirs ZEPHYR_MCUBOOT_MODULE_DIR=/__w/weather-station/bootloader/mcuboot)
list(APPEND kconfig_env_dirs ZEPHYR_NANOPB_MODULE_DIR=/__w/weather-station/modules/lib/nanopb)
list(APPEND kconfig_env_dirs ZEPHYR_SEGGER_MODULE_DIR=/__w/weather-station/modules/debug/segger)
list(APPEND kconfig_env_dirs ZEPHYR_TF_PSA_CRYPTO_MODULE_DIR=/__w/weather-station/modules/crypto/tf-psa-crypto)
